version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    user: "${UID_GID}"

  # WEBa
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  # React
  node:
    build: ./infra/node
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"

  # DB
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
